language: objective-c
osx_image: xcode9

# cache: cocoapods
# podfile: Example/Podfile

before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
# Build cocoapods example project
# - set -o pipefail && xcodebuild -workspace Example/xDripG5.xcworkspace -scheme xDripG5-Example -sdk iphonesimulator -destination name="iPhone SE" ONLY_ACTIVE_ARCH=NO | xcpretty
# Build Travis project and run tests
- xcodebuild -project xDripG5.xcodeproj -scheme xDripG5 -sdk iphonesimulator11.0 build -destination name="iPhone SE" test
# - pod lib lint
